#! /bin/sh

# Start Serf
join_list=""

if [ -n "${JOIN_LIST}" ]; then
  for host in $(echo ${JOIN_LIST} | tr ',' ' '); do
    join_list="${join_list} --join ${host}" 
  done
fi

exec /sbin/setuser serf /usr/bin/serf agent \
  ${join_list} \
  -node "${NODE_NAME:-$(hostname -s)}" \
  -bind "0.0.0.0:${BIND_PORT:-7946}" \
  -advertise "${HOST_IP:-$(hostname -i | awk '{print $1}')}:${BIND_PORT:-7946}" \
  -event-handler /etc/service/serf/dispatcher.sh \
  -log-level=debug \
  >> /var/log/serf.log 2>&1
